"""change:model

Revision ID: 205f253346e2
Revises: 4749d50a3f32
Create Date: 2024-11-25 14:51:40.555557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '205f253346e2'
down_revision: Union[str, None] = '4749d50a3f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'api_type',
               existing_type=postgresql.ENUM('openai', 'google', 'azure', name='modeltypes'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'api_type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('openai', 'google', 'azure', name='modeltypes'),
               existing_nullable=False)
    # ### end Alembic commands ###
