"""change:change_api_type_to_string

Revision ID: 4749d50a3f32
Revises: 4382780d3170
Create Date: 2024-11-25 14:47:52.222050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4749d50a3f32'
down_revision: Union[str, None] = '4382780d3170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'api_type',
               existing_type=postgresql.ENUM('openai', 'google', 'azure', name='modeltypes'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('model', 'api_type',
               existing_type=postgresql.ENUM('openai', 'google', 'azure', name='modeltypes'),
               nullable=True)
    # ### end Alembic commands ###
